set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set -g allow-passthrough on

set -g status-position top
set -g status-interval 1

set -g status-left-length 50
set -g status-right-length 100

set -g status-left "#[fg=black,bg=cyan] #S #[default]"

set -g status-right "#(date '+%H:%M')"


bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2
