
background:     #1B1E31
foreground:     #F8F8F2

color0:         #191A21
color8:         #4D4D4D

color1:         #FF5555
color9:         #FF6E6E

color2:         #50FA7B
color10:        #69FF94

color3:         #F1FA8C
color11:        #FFFFA5

color4:         #BD93F9
color12:        #D6ACFF

color5:         #FF79C6
color13:        #FF92DF

color6:         #8BE9FD
color14:        #A4FFFF

color7:         #ABB2BF
color15:        #FFFFFF
