no-video
keep-open=yes

audio-channels=auto
audio-normalize-downmix=yes

opensles-buffer-size-in-ms=500

audio-samplerate=48000

audio-resample-filter-size=32
audio-resample-phase-shift=24
audio-resample-cutoff=0.97
audio-resample-linear=no

replaygain=album

af=lavfi=[alimiter=limit=0.95]

terminal=yes
msg-level=all=warn
