music_directory     "~/storage"

db_file             "~/.mpd/database"
playlist_directory  "~/.mpd/playlists"

log_file            "~/.mpd/log"
pid_file            "~/.mpd/pid"
state_file          "~/.mpd/state"

bind_to_address     "127.0.0.1"
port                "6600"

auto_update         "yes"

audio_output {
    type    "fifo"
    name    "MPV Output"
    path    "/data/data/com.termux/files/home/.mpd/mpd.fifo"
    format  "44100:16:2"
}

audio_output {
    type    "fifo"
    name    "Visualizer"
    path    "/data/data/com.termux/files/home/.mpd/visualizer.fifo"
    format  "44100:16:2"
}

#audio_output {
#    type "pulse"
#    name "PulseAudio"
#}

